<?php
// File: my_hooks_demo/my_hooks_demo.module

use Drupal\User\UserInterface;

/**
 * Implements hook_user_login().
 */
Function my_hooks_demo_user_login(UserInterface $account) {
    $user = $account->getDisplayName();
  \Drupal::messenger()->addMessage(t("Welcome @username. Welcome back!!!", ['@username' => $user]));
}   

Function my_hooks_demo_cache_flush() {
    // $user = $account->getDisplayName();
  \Drupal::messenger()->addMessage('You flushed the cache!');
}   
